version: "3.8"
services:
  backend:
    build:
      context: ./azure-app-server
    container_name: dotnet-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=azure-app-db.postgres.database.azure.com;Port=5432;Database=postgres;Username=postgres;Password=postgres;SslMode=Require
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./azure-app-client
    container_name: remix-frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8080
    ports:
      - "3000:3000"
