name: Build and Deploy Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'azure-app-client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./azure-app-client
          push: true
          tags: |
            alvarotoroeafit/azure-app-client:latest
            alvarotoroeafit/azure-app-client:${{ github.sha }}
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: azure-app-client
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_CLIENT }}
          images: alvarotoroeafit/azure-app-client:latest 